[solution]
values = [
["2", "1", "5", "3", "7", "9", "8", "6", "4"],
["9", "8", "6", "1", "2", "4", "3", "5", "7"],
["7", "3", "4", "8", "5", "6", "2", "1", "9"],
["4", "5", "2", "7", "8", "1", "6", "9", "3"],
["8", "6", "9", "5", "4", "3", "1", "7", "2"],
["3", "7", "1", "6", "9", "2", "4", "8", "5"],
["5", "2", "7", "4", "1", "8", "9", "3", "6"],
["6", "4", "8", "9", "3", "7", "5", "2", "1"],
["1", "9", "3", "2", "6", "5", "7", "4", "8"],
]
